version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for easy setup
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory usage
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

#  /ollama:/root/.ollama -p 11434:11434 ollama/ollama
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - elk

networks:
  elk:
    driver: bridge
